<a href="https://colab.research.google.com/github/Mark-Barbaric/Introduction_To_Machine_Learning/blob/master/Session3/Intro_To_Machine_Learning_W3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt

#neural net library
import keras
from keras.models import Sequential 
from keras.layers import Dense

from sklearn.datasets import load_boston
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [0]:
boston = load_boston()
boston_df = pd.DataFrame(boston.data, columns=boston.feature_names)

In [0]:
boston_df

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [0]:
target = boston.target

In [0]:
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [0]:
#boston_df["target"] = target

In [0]:
boston_df

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [0]:
x_train, x_test, y_train, y_test = train_test_split(boston_df, target, train_size=0.7)

In [0]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=20, activation="relu", kernel_initializer='normal', input_shape=x_train.shape[1:]),
    tf.keras.layers.Dense(units=5, activation='relu'),
    tf.keras.layers.Dense(units=1, activation='linear', kernel_initializer='normal')
])

In [0]:
model.compile(optimizer="adam", loss="mse", metrics=["mse"])

#model.compile(optimizer="rmsprop", loss="mse", metrics=["mse"])

In [0]:
model.fit(x_train, y_train, epochs=200)

Epoch 1/200
12/12 [==============================] - 0s 1ms/step - loss: 606.1769 - mse: 627.4782
Epoch 2/200
12/12 [==============================] - 0s 2ms/step - loss: 605.8250 - mse: 619.7571
Epoch 3/200
12/12 [==============================] - 0s 1ms/step - loss: 585.4783 - mse: 600.4167
Epoch 4/200
12/12 [==============================] - 0s 1ms/step - loss: 442.8043 - mse: 473.4231
Epoch 5/200
12/12 [==============================] - 0s 1ms/step - loss: 278.5149 - mse: 261.0677
Epoch 6/200
12/12 [==============================] - 0s 1ms/step - loss: 135.9202 - mse: 146.2996
Epoch 7/200
12/12 [==============================] - 0s 1ms/step - loss: 128.8743 - mse: 139.7145
Epoch 8/200
12/12 [==============================] - 0s 1ms/step - loss: 113.9183 - mse: 122.5223
Epoch 9/200
12/12 [==============================] - 0s 1ms/step - loss: 104.7318 - mse: 113.5013
Epoch 10/200
12/12 [==============================] - 0s 1ms/step - loss: 98.0879 - mse: 105.8898
Epoch 11/200
12/12 [

In [0]:
scores = model.evaluate(x_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

5/5 [==============================] - 0s 2ms/step - loss: 27.8793 - mse: 28.2541

mse: 2825.41%


In [0]:
model.predict(x_train)

array([[22.020031 ],
       [25.946747 ],
       [26.075787 ],
       [34.404068 ],
       [21.976913 ],
       [13.810896 ],
       [17.047897 ],
       [20.207392 ],
       [23.485575 ],
       [15.452204 ],
       [30.52341  ],
       [21.417397 ],
       [20.634132 ],
       [15.148465 ],
       [15.406035 ],
       [16.654102 ],
       [20.08827  ],
       [23.743643 ],
       [21.19061  ],
       [16.644514 ],
       [28.73904  ],
       [31.113892 ],
       [15.660233 ],
       [18.067629 ],
       [15.937073 ],
       [31.029663 ],
       [40.942886 ],
       [26.061127 ],
       [24.843117 ],
       [20.966871 ],
       [29.214548 ],
       [24.384418 ],
       [17.397923 ],
       [21.75069  ],
       [32.784424 ],
       [25.886988 ],
       [ 9.950233 ],
       [ 9.405524 ],
       [10.430118 ],
       [36.270996 ],
       [23.90149  ],
       [16.805212 ],
       [21.119238 ],
       [28.106617 ],
       [20.274397 ],
       [20.583317 ],
       [18.125746 ],
       [15.82

In [0]:
y_train

array([21.4, 23.7, 26.6, 27.9, 28.1, 13.3, 19.3, 21.2, 23.1, 17.4, 33.2,
       21.4, 19.3, 15.2, 19.5, 20. , 19.6, 22. , 22. , 20.1, 22.9, 24.6,
       19.9, 19.9, 13.3, 32.9, 50. , 22. , 26.2, 18.7, 32.2, 27.5, 23.8,
       24.5, 39.8, 20.5,  5. , 10.4,  8.3, 44.8, 26.4, 20.8, 23.1, 28.7,
       21.5, 14.5, 21.9,  7.2, 10.9, 15.6, 17.6, 24. , 42.8, 36. , 13.8,
       21. , 19.6, 17.9, 15. , 25. , 15.4, 20.1, 43.8, 17.2, 16.1, 12.1,
       42.3, 50. , 50. , 20.6, 19. , 28.4, 27. , 30.7, 36.5, 19.5, 28. ,
       34.6, 15.2, 23.2, 15.3, 19.4, 16.2, 22.5, 50. , 18.9, 16.3, 23.1,
       44. , 23. , 19. , 36.1, 22.4, 19.2, 14.9, 12. , 20.2, 17.5, 21.7,
       17.8, 22.6,  7.2, 19.8, 23.3, 23.6, 50. ,  7.2, 22.8, 46. ,  7. ,
       15.6, 18.7, 21.9, 35.1, 10.2, 22.7, 37.3, 25.3, 21.4, 24.8, 18.8,
       12.7, 17.1, 18.5, 23.7, 28.7, 36.2, 34.9, 23.3, 28.7, 14.6, 17.3,
       28.6, 19.4,  7.5, 18.4, 19.5, 22.3, 27.1, 10.2, 18.1, 21.7, 12.7,
       26.4, 20.2, 24.3, 18.2,  8.7, 20.8,  7.4, 34